name: BigCities
main: net.mayateck.BigCities.BigCities
version: 0.03.02Alpha
description: 'BigCities - City-based Factions/Towny alternative.'
website: 'https://github.com/Wehttam664/BigCities/wiki'
author: Wehttam664
softdepend: [TagAPI, Vault]
loadbefore: [Factions, Towny]
commands:
   city:
      description: 'BigCities core command.'
      aliases: c
      permission: bigcities.city
      permission-message: 'You cannot access BigCities commands with your current permissions.'
      usage: 'Un-handled Syntax Issue: Try /<command> help.'
permissions:
   bigcities.*:
      description: 'Global permissions for BigCities'
      children:
         bigcities.city: true
         bitcities.nation: true
         bigcities.admin: false
   bigcities.city:
      description: 'City commands for BigCities'
      default: true
      children:
         bigcities.city.found: true
         bigcities.city.claim: true
         bigcities.city.disband: true
         bigcities.city.invite: true
         bigcities.city.createrank: true
         bigcities.city.setrank: true
         bigcities.city.leave: true
         bigcities.city.ally: true
         bigcities.city.war: true
         bigcities.city.neutral: true
         bigcities.city.kick: true
         bigcities.city.rename: true
         bigcities.city.description: true
         bigcities.city.home: true
         bigcities.city.sethome: true
   bigcities.admin:
      description: 'Admin command for BigCities'
      default: false
      children:
         bigcities.admin.bypass: false
         bigcities.admin.delete: false
         bigcities.admin.tweak: false
         bigcities.admin.modifyprotected: false
         bigcities.admin.modifyebarrens: false
   